name: Update README

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build
      run: |
        npm install
        gulp

    - name: Commit
    run: |
        git config --global user.name 'Kyle Martinez'
        git config --global user.email 'kyletmartinez@users.noreply.github.com'
        git commit -am "Update README.md"
        git push
