name: Update documentation

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - uses: actions/setup-node

      - name: Install node
        run: npm ci

      - name: Run gulp
        run: gulp
